### PR TITLE
Fixed bug with gcc version retrieval

### LINKED ISSUE #7: Error installing plugin
I have a problem when installing the `scipion-em-isonet` pluging, specifically in the binary installation. It happens both in stable and devel:

```
Couldn't get binaries definition of  plugin: Invalid version: 'Copyright'
Traceback (most recent call last):
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/miniconda/miniconda3/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_funcs.py", line 334, in getInstallenv
    plugin.defineBinaries(env)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/scipion/plugins/scipion-em-isonet/isonet/__init__.py", line 131, in defineBinaries
    cls.addIsonetPackage(env)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/scipion/plugins/scipion-em-isonet/isonet/__init__.py", line 96, in addIsonetPackage
    cudalib = utils.CudaLibs().getCudaLibraries(cudaVersion)
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/scipion/plugins/scipion-em-isonet/isonet/utils.py", line 59, in getCudaLibraries
    if parse_version(gccMatch).major <= parse_version(gccVersion).major:
  File "/scicore/home/engel0006/GROUP/pool-engel/soft/miniconda/miniconda3/envs/scipion3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'Copyright'
diogori@worker08:plugins$ which gcc
/scicore/soft/apps/GCCcore/10.3.0/bin/gcc
diogori@worker08:plugins$ gcc --version
gcc (GCC) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The issue is specifically that the plugin is looking for the gcc version in the wrong place. This is an easy fix and I'll make a PR right away, but wanted to document the issue here.

### PR DESCRIPTION
**Pull request by rdrighetto**
Fixes #7

### CODE REVIEW

**Comment by azazellochg** [comment]
what about using https://github.com/scipion-em/scipion-em-pyseg/pull/78 approach instead? :)

**Comment by fonsecareyna82** [comment]
Could you put a print on line 57 of utils.py and tell me the value of gccVersion ?
in my case it returns this and the gcc version value comes in position 3:

['gcc', '(Ubuntu', '10.5.0-1ubuntu1~22.04)', **'10.5.0'**, 'Copyright', '(C)', '2020', 'Free', 'Software', 'Foundation,', 'Inc.', 'This', 'is', 'free', 'software;', 'see', 'the', 'source', 'for', 'copying', 'conditions. ', 'There', 'is', 'NO', 'warranty;', 'not', 'even', 'for', 'MERCHANTABILITY', 'or', 'FITNESS', 'FOR', 'A', 'PARTICULAR', 'PURPOSE.']

**Comment by rdrighetto** [comment]
Hi Yunior, this is the output that I get. In my case the version comes in position [2]:

`['gcc', '(GCC)', '10.3.0', 'Copyright', '(C)', '2020', 'Free', 'Software', 'Foundation,', 'Inc.', 'This', 'is', 'free', 'software;', 'see', 'the', 'source', 'for', 'copying', 'conditions.', 'There', 'is', 'NO', 'warranty;', 'not', 'even', 'for', 'MERCHANTABILITY', 'or', 'FITNESS', 'FOR', 'A', 'PARTICULAR', 'PURPOSE.']`

**Comment by fonsecareyna82** [comment]
hahahaha, don't worry, I will solve this problem very quickly.

**Pull request closed without merging**
